[package]
name = "hugin"
version = "0.2.4"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
chrono-tz = "0.6.1"
diesel = { version = "1.4.8", features = ["chrono", "postgres"], optional = true }
futures = "0.3.21"
reqwest = { version = "0.11.11", features = ["json"] }
select = "0.5.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_urlencoded = "0.7.1"
strum = { version = "0.24.1", features = ["derive"] }
thiserror = "1.0.31"
tracing = "0.1.34"
url = "2.2.2"
urlencoding = "2.1.0"
uuid = { version = "0.8.2", features = ["v5"] }

[dev-dependencies]
serde_json = "1.0.81"
tokio = { version = "1.20.1", features = ["rt", "macros"] }
tokio-test = "0.4.2"

[features]
