[package]
name = "menu-proxy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.5.4"
actix-rt = "1"
actix-web = "3.3.2"
chrono = { version = "0.4.19", features = ["serde"] }
futures = "0.3.15"
lazy_static = "1.4.0"
reqwest = { version =  "0.10", features = ["json"] }
scraper = "0.12.0"
serde = { version = "1.0.126", features = ["derive"] }
thiserror = "1.0.26"

[dev-dependencies]
serde_json = "1.0.64"
