[workspace]
members = ["euphemism", "munin", "stor"]

[workspace.dependencies]
clap = "4.0.18"
meilisearch-sdk = { version = "0.20.1", default-features = false }
stor = { path = "stor" }
uuid = "1.2.2"
