[workspace]
members = ["euphemism", "munin", "oden-http", "stor"]

[workspace.dependencies]
chrono = "0.4.22"
chrono-tz = "0.8.0"
clap = "4.0.18"
meilisearch-sdk = { version = "0.20.1", default-features = false }
stor = { path = "stor" }
uuid = "1.2.2"
