[package]
name = "menu-proxy"
version = "1.3.1"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.3.2"
chrono = { version = "0.4.19", features = ["serde"] }
const_format = "0.2.22"
env_logger = "0.9.0"
futures = "0.3.17"
lazy_static = "1.4.0"
log = "0.4.14"
reqwest = { version =  "0.10.10", features = ["json"] }
scraper = "0.12.0"
serde = { version = "1.0.130", features = ["derive"] }
strum = { version = "0.22.0", features = ["derive"] }
thiserror = "1.0.26"
url = "2.2.2"
urlencoding = "2.1.0"

[dev-dependencies]
serde_json = "1.0.68"
