version: "3.8"

services:
  menu-proxy:
    build: .
    healthcheck:
      test: ["CMD", "curl", "-f", "http://menu-proxy/health"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      menu-proxy:
        condition: service_healthy
