[package]
name = "oden-http"
version = "0.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2.3.0"
actix-web = "4.0.0-beta.12"
munin-lib = { path = "../munin-lib", version = "0.2.0" }
chrono = "0.4.19"
chrono-tz = "0.6.0"
futures = "0.3.17"
serde = { version = "1.0.130", features = ["derive"] }
thiserror = "1.0.30"
tracing-subscriber = { version = "0.3.1", features = ["env-filter"] }
database = { path = "../database", version = "0.2.0" }
diesel = { version = "1.4.8", features = ["r2d2"] }
structopt = "0.3.25"
dotenv = "0.15.0"
r2d2 = "0.8.9"
tracing = "0.1.29"
