[package]
name = "munin"
version = "0.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
database = { path = "../database", features = ["meilisearch-sdk"], version = "0.2.0" }
munin-lib = { path = "../munin-lib", features = ["diesel"], version = "0.2.0" }
chrono = "0.4.19"
chrono-tz = "0.6.0"
diesel = { version = "1.4.8", features = ["postgres", "chrono"] }
dotenv = "0.15.0"
futures = "0.3.17"
meilisearch-sdk = "0.11.0"
serde = { version = "1.0.130", features = ["derive"] }
structopt = "0.3.25"
thiserror = "1.0.30"
tokio = { version = "1.13.0", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.1", features = ["env-filter"] }
