[package]
name = "munin"
version = "0.2.5"
edition = "2021"

[dependencies]
hugin = { path = "../hugin", version = "0.2.4" }
dotenv = "0.15.0"
thiserror = "1.0.31"
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
anyhow = "1.0.57"
clap = { version = "3.2.22", features = ["derive", "env"] }
tokio = { version = "1.21.1", features = ["full"] }
tempfile = "3.3.0"
git2 = "0.15.0"
futures = "0.3.24"
rmp-serde = "1.1.0"
uuid = { version = "0.8", features = ["serde"] }
minicbor = { version = "0.18.0", features = ["derive", "std"] }
serde = { version = "1.0.145", features = ["derive"] }
csv = "1.1.6"
chrono = "0.4.22"
chrono-tz = "0.6.3"

[features]
