[package]
name = "munin"
version = "0.2.3"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
database = { path = "../database", features = ["meilisearch-sdk"], version = "0.2.3" }
munin-lib = { path = "../munin-lib", features = ["diesel"], version = "0.2.3" }
chrono = "0.4.19"
chrono-tz = "0.6.1"
diesel = { version = "1.4.8", features = ["postgres", "chrono"] }
dotenv = "0.15.0"
futures = "0.3.21"
meilisearch-sdk = "0.17.0"
serde = { version = "1.0.137", features = ["derive"] }
structopt = "0.3.26"
thiserror = "1.0.30"
tokio = { version = "1.16.1", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
anyhow = "1.0.57"
flate2 = "1.0.22"
csv = "1.1.6"
serde_json = "1.0.78"

[features]
