[package]
name = "munin"
version = "0.2.6"
edition = "2021"

[dependencies]
database = { path = "../database", features = ["meilisearch-sdk"], version = "0.2.3" }
hugin = { path = "../hugin", features = ["diesel"], version = "0.2.4" }
chrono = "0.4.19"
chrono-tz = "0.6.1"
diesel = { version = "1.4.8", features = ["postgres", "chrono"] }
dotenv = "0.15.0"
futures = "0.3.21"
meilisearch-sdk = "0.20.1"
serde = { version = "1.0.147", features = ["derive"] }
thiserror = "1.0.31"
tokio = { version = "1.16.1", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
anyhow = "1.0.57"
csv = "1.1.6"
serde_json = "1.0.81"
sentry-tracing = "0.27.0"
sentry = "0.27.0"
clap = { version = "4.0.18", features = ["derive", "env"] }
