name: CI

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16

      - uses: actions/cache@v2.1.4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install --frozen-lockfile

      - run: yarn lint

  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16

      - uses: actions/cache@v2.1.4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install --frozen-lockfile

      - run: yarn prettier . --check

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16

      - uses: actions/cache@v2.1.4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install --frozen-lockfile

      - run: yarn test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  docker-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: docker-compose build

      - run: docker-compose run test
