name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: prep
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/tags/v}

      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/skolorna/menu-proxy:${{ steps.prep.outputs.version }}
            ghcr.io/skolorna/menu-proxy:latest
