name: Docker

on: [push]

jobs:
  hugin:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - id: prep
        working-directory: ./hugin
        run: |
          echo ::set-output name=version::$(cargo pkgid | cut -d "#" -f2 -)
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          file: ./hugin/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/skolorna/hugin:${{ steps.prep.outputs.version }}
            ghcr.io/skolorna/hugin:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  oden-http:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - id: prep
        working-directory: ./oden-http
        run: |
          echo ::set-output name=version::$(cargo pkgid | cut -d "#" -f2 -)
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          file: ./oden-http/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/skolorna/oden-http:${{ steps.prep.outputs.version }}
            ghcr.io/skolorna/oden-http:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
